# Generated by Django 5.0.6 on 2024-05-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Technologies",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="technology_used",
        ),
        migrations.AddField(
            model_name="project",
            name="technology_used",
            field=models.ManyToManyField(related_name="projects", to="core.technology"),
        ),
    ]
