# Generated by Django 5.0.2 on 2024-05-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_technology_remove_project_technology_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tag',
        ),
    ]
