# Generated by Django 5.0.2 on 2024-05-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='user',
        ),
    ]
