# Generated by Django 5.0.2 on 2024-05-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_representative_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='profile_pic',
        ),
    ]
