# Generated by Django 5.0.6 on 2024-05-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authusers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
