# Generated by Django 5.0.2 on 2024-06-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0002_alter_user_bio_alter_user_city_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='profile-photos'),
        ),
    ]
